MVCRealtimeSignalR/Controllers/StudentController.cs
using MVCRealtimeSignalR.Hubs;
using MVCRealtimeSignalR.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCRealtimeSignalR.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAllStudent()
        {
            try
            {
                List<STUDENT> data = new List<STUDENT>();
                using (DBDataContext SQL = new DBDataContext())
                {
                    data = SQL.STUDENTs.ToList();
                }
                return Json(new { Status = true, Data = data, Message = "OK" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { Status = false, Message = "False cmnr" }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult CreateStudent(STUDENT data)
        {
            try
            {
                using (DBDataContext SQL = new DBDataContext())
                {
                    SQL.STUDENTs.InsertOnSubmit(data);
                    SQL.SubmitChanges();
                }
                EmployeesHub.BroadcastData();
                return Json(new { Status = true, Data = data, Message = "OK" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { Status = false, Message = "False cmnr" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

MVCRealtimeSignalR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVC SignalR Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("JavaScript", required: false)
    
</head>
<body>
   
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Employees", "Index", "Student")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @{
                var WebBrowserName = HttpContext.Current.Request.Browser.Browser;
                <p>&copy; @DateTime.Now.Year - MVC SignalR Application</p>
                <p style="color:blue; background-color:yellow; font-size:18px;">(Browser :@WebBrowserName)</p>
            }
        </footer>
    </div>

    
</body>
</html>

<script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
<script src="/signalr/hubs"></script>